name: ci

on: [ push ]

env:
  JAVA_VERSION: 17

jobs:



  Android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        androidBuildVariant: [ Debug, Release ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assemble${{ matrix.androidBuildVariant }} --stacktrace



  Desktop:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew composeApp:desktopJar --stacktrace



  Browser:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew :composeApp:wasmJsBrowserDevelopmentWebpack --stacktrace



  iOS:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciIos --stacktrace
